### ISSUE TITLE
Line 284

### ISSUE THREAD

**Issue by Jone-Luo** [TeaPearce/Conditional_Diffusion_MNIST#10]
Hi,

Thanks for your code. I have one question about the reason why we need to caculate 'z' caculated in line 284: z = torch.randn(n_sample, *size).to(device) if i > 1 else 0.

**Comment by ChenLiangYin** [comment]
> Hi,
> 
> Thanks for your code. I have one question about the reason why we need to caculate 'z' caculated in line 284: z = torch.randn(n_sample, *size).to(device) if i > 1 else 0.

I think that is because we don't need to add noise at the last step in sampling.

**Comment by qin-jingyun** [comment]
> Hi,
> 
> Thanks for your code. I have one question about the reason why we need to caculate 'z' caculated in line 284: z = torch.randn(n_sample, *size).to(device) if i > 1 else 0.

Refer to this Algorithm in DDPM pls:
![image](https://github.com/TeaPearce/Conditional_Diffusion_MNIST/assets/73811180/a1320d5d-639d-4752-8c99-4b1e3f43f012)
