### ISSUE TITLE
If we parameterize xθ in terms of x0-prediction, how to achieve it?

### ISSUE THREAD

**Issue by greens007** [TeaPearce/Conditional_Diffusion_MNIST#3]
Hi,
If we parameterize xθ in terms of x0-prediction, how to implement the inference of classifier-free guidance? The original paper only parameterizes xθ in terms of ε-prediction.

**Comment by TeaPearce** [comment]
Hi, I only looked at $\epsilon$ prediction here, but I imagine a similar combination could be used?
