### ISSUE TITLE
minimal evaluation

### ISSUE THREAD

**Issue by dgm2** [TeaPearce/Conditional_Diffusion_MNIST#6]
Hi 
Thanks for this code.
What you suggest for evaluating this conditional generation?
E.g. what is the easiest code change to get a meaningful evaluation with some metrics (e.g. what about FID)
Any suggestion on which metric could be suitable here

Best regards

**Comment by TeaPearce** [comment]
I think FID would make sense. Inception score etc also fine. I don't plan on implementing this, but I'm sure there are some easy packages out there that do this already (e.g. https://github.com/mseitzer/pytorch-fid)
