### ISSUE TITLE
where is "Puncond"?

### ISSUE THREAD

**Issue by qingninggo** [TeaPearce/Conditional_Diffusion_MNIST#7]
Where is the “Puncond”in the original paper, please!

**Comment by Alienge** [comment]
This author writes this code clearly what I have seen.  I think the Puncond is here in training 

https://github.com/TeaPearce/Conditional_Diffusion_MNIST/blob/3b7aa12ba78b2b9367e7de801c6586f90339a29e/script.py#L249

Sampling is here

https://github.com/TeaPearce/Conditional_Diffusion_MNIST/blob/3b7aa12ba78b2b9367e7de801c6586f90339a29e/script.py#L266-L272

**Comment by TeaPearce** [comment]
Indeed, `self.drop_prob` is the probability of unconditional training.
