### ISSUE TITLE
About performance improvement

### ISSUE THREAD

**Issue by Pragmatism0220** [TeaPearce/Conditional_Diffusion_MNIST#8]
Hello, thank you for your excellent work!
I am a green hand in diffusion model.
If I want to further improve the performance of model, what parameters and network structure do I need to modify? Do you have any suggestions? Thank you!

**Comment by TeaPearce** [comment]
I'd suggest looking into sota U-net architectures (this one didn't have attention or anything like that). Could also take a look at more recent training / sampling schemes, e.g. Karras [https://arxiv.org/abs/2206.00364](url).
